apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: documind-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: documind.demotao.top
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: documind-frontend
            port:
              number: 80
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: documind-backend
            port:
              number: 8080
      - path: /ai/
        pathType: Prefix
        backend:
          service:
            name: documind-ai-engine
            port:
              number: 8000
